# Workflow name
name: "Chromatic for Isomer Components"

# Event for the workflow
on:
  pull_request:
    types: [opened, reopened, synchronize]

  push:
    branches:
      - main

# List of jobs
jobs:
  chromatic:
    # Operating System
    runs-on: ubuntu-latest
    # Only run if the user is not a bot
    if: ${{ !endsWith(github.actor , 'bot') }}
    environment: staging
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # 👈 Required to retrieve git history

      - name: Check for changes
        uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            components:
              - '.github/workflows/chromatic.yml'
              - 'packages/components/.storybook/**'
              - 'packages/components/src/**'
              - 'packages/components/package.json'
              - 'packages/components/package-lock.json'
              - 'packages/components/tailwind.config.js'

      - name: Set environment variable to run Chromatic build
        if: ${{ steps.filter.outputs.components == 'true' }}
        run: echo "ISOMER_RUN_CHROMATIC_BUILD=true" >> $GITHUB_ENV

      # This extra step is not in the original chromatic workflow.
      # This is to pin the version of node (18.x) used.
      - name: Setup Node.js
        if: ${{ env.ISOMER_RUN_CHROMATIC_BUILD == 'true' }}
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          cache: "npm"

      - name: Install dependencies
        if: ${{ env.ISOMER_RUN_CHROMATIC_BUILD == 'true' }}
        run: npm ci

      # 👇 Adds Chromatic as a step in the workflow
      - name: Publish to Chromatic
        if: ${{ env.ISOMER_RUN_CHROMATIC_BUILD == 'true' }}
        uses: chromaui/action@v1
        # Chromatic GitHub Action options
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # 👇 Chromatic projectToken, refer to the manage page to obtain it.
          projectToken: ${{ secrets.CHROMATIC_COMPONENTS_PROJECT_TOKEN }}
          # onlyChanged: true
          branchName: ${{ github.ref_name }}
          autoAcceptChanges: main
          workingDir: packages/components
